# Generated by Django 3.2.20 on 2023-07-14 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('phoneno', models.BigIntegerField(default=0)),
                ('password', models.CharField(max_length=128)),
                ('val', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='TodoTask',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('taskTest', models.CharField(max_length=400)),
                ('createdTime', models.DateTimeField()),
                ('updatedTime', models.DateTimeField()),
                ('checkedTime', models.DateTimeField()),
                ('deletedTime', models.DateTimeField()),
                ('serial', models.IntegerField(default=0)),
                ('status_c', models.BooleanField()),
                ('status_d', models.BooleanField()),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.register')),
            ],
        ),
    ]
