# Generated by Django 2.0 on 2023-07-14 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20230714_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todotask',
            name='createdTime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
