# Generated by Django 2.0 on 2023-07-14 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20230714_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todotask',
            name='checkedTime',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='todotask',
            name='createdTime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='todotask',
            name='deletedTime',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='todotask',
            name='updatedTime',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
